# Path to sources
sonar.sources=static/book-blog/src/
sonar.exclusions=static/book-blog/src/**/*.test.tsx
sonar.modules=components,containers

# Path to tests
sonar.tests=static/book-blog/src/
sonar.test.inclusions=static/book-blog/src/**/*.test.tsx
# Source encoding
# sonar.sourceEncoding=
sonar.pullrequest.key=${pr.key}
sonar.pullrequest.branch=${pr.branch}
sonar.pullrequest.base=${pr.base}

# Exclusions for copy-paste detection
# sonar.cpd.exclusions=

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.file.suffixes=.js,.jsx
