name: Book Blog
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
		with:
		  projectBaseDir: static/
		  
	name: ❇️ Setup Nodejs
		  uses: actions/setup-node@v3.5.1
		  
  	name: 📦 Install dependencies
          run: |
            yarn install
		    
  	name: 📦 Run tests
		run: |
        	yarn test
		  
  	name: Build and analyze
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          run: mvn verify sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=patpattypat \
            -Dsonar.projectKey=patpattypat_BookBlog